import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import {
  Activity, Ambulance, Bell, Building2, ChevronRight, CircleDot, Clock3,
  Command, Crosshair, Gauge, Hospital, LayoutDashboard, MapPinned, Menu,
  MoreHorizontal, Navigation, Radio, Settings, ShieldCheck, Signal, Siren,
  SlidersHorizontal, Sparkles, Timer, TrafficCone, TrendingUp, TriangleAlert,
  Users, X, Zap
} from "lucide-react";

const navItems = [
  { label: "Command Center", icon: LayoutDashboard, active: true },
  { label: "Live Operations", icon: Radio },
  { label: "Ambulances", icon: Ambulance },
  { label: "Traffic Signals", icon: Signal },
  { label: "Green Corridors", icon: Navigation },
  { label: "Hospitals", icon: Hospital },
  { label: "Analytics", icon: TrendingUp },
  { label: "Settings", icon: Settings },
];

const emergencies = [
  { priority: "P1", id: "AMB-102", destination: "City General Hospital", eta: "04:32", status: "Corridor active", tone: "coral" },
  { priority: "P2", id: "AMB-087", destination: "St. Mary’s Trauma Center", eta: "08:15", status: "En route", tone: "amber" },
  { priority: "P2", id: "AMB-114", destination: "Metropolitan Medical", eta: "12:48", status: "Preparing route", tone: "amber" },
  { priority: "P3", id: "AMB-061", destination: "Eastside Community Hospital", eta: "18:20", status: "Monitoring", tone: "cyan" },
];

function MetricCard({ icon: Icon, label, value, detail, accent = "cyan" }: { icon: any; label: string; value: string; detail: string; accent?: string }) {
  const accentClass = accent === "green" ? "text-[#5be6a8]" : accent === "coral" ? "text-[#ff806e]" : "text-[#48d7e8]";
  return <div className="panel panel-hover relative overflow-hidden rounded-xl p-4 sm:p-5">
    <div className="absolute -right-5 -top-7 h-24 w-24 rounded-full bg-[#48d7e8]/5 blur-2xl" />
    <div className="relative flex items-start justify-between gap-3">
      <div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#76939c]">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-white sm:text-[30px]">{value}</p></div>
      <div className={`rounded-lg border border-white/10 bg-white/[.035] p-2 ${accentClass}`}><Icon size={17} strokeWidth={1.7} /></div>
    </div>
    <div className="relative mt-3 flex items-center justify-between gap-2 text-[11px] text-[#76939c]"><span className="flex items-center gap-2"><span className={`h-1.5 w-1.5 rounded-full ${accent === "green" ? "bg-[#5be6a8]" : accent === "coral" ? "bg-[#ff806e]" : "bg-[#48d7e8]"}`} />{detail}</span><span className="mono text-[9px] text-[#496d76]">LIVE / 01s</span></div>
  </div>;
}

function SectionTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action?: string }) {
  return <div className="mb-4 flex items-end justify-between gap-3"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#48d7e8]">{eyebrow}</p><h2 className="mt-1 text-[17px] font-semibold tracking-[-.02em] text-white">{title}</h2></div>{action && <button onClick={() => toast.info(`${action} view is available in the full operations suite.`)} className="mono flex items-center gap-1 text-[10px] uppercase tracking-[.12em] text-[#76939c] transition-colors hover:text-[#48d7e8]">View all <ChevronRight size={13}/></button>}</div>;
}

function StatusPill({ children, tone = "cyan" }: { children: React.ReactNode; tone?: "cyan" | "green" | "amber" | "coral" | "muted" }) {
  const colors = { cyan: "border-[#48d7e8]/25 bg-[#48d7e8]/[.08] text-[#72e2ed]", green: "border-[#5be6a8]/25 bg-[#5be6a8]/[.08] text-[#5be6a8]", amber: "border-[#f5ba69]/25 bg-[#f5ba69]/[.08] text-[#f5ba69]", coral: "border-[#ff806e]/25 bg-[#ff806e]/[.08] text-[#ff9688]", muted: "border-white/10 bg-white/[.04] text-[#92aab0]" };
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2 py-1 mono text-[9px] uppercase tracking-[.08em] ${colors[tone]}`}><span className={`h-1.5 w-1.5 rounded-full ${tone === "green" ? "bg-[#5be6a8]" : tone === "amber" ? "bg-[#f5ba69]" : tone === "coral" ? "bg-[#ff806e]" : tone === "cyan" ? "bg-[#48d7e8]" : "bg-[#92aab0]"}`} />{children}</span>;
}

function LiveMap({ progress }: { progress: number }) {
  const ambulanceX = 130 + progress * 1.55;
  const ambulanceY = 305 - progress * 0.98;
  return <div className="panel telemetry-grid relative min-h-[360px] overflow-hidden rounded-xl sm:min-h-[430px]">
    <div className="absolute inset-0 opacity-80" style={{ backgroundImage: "url('/manus-storage/lifelane-grid-texture_ab6daa6e.png')", backgroundSize: "cover", mixBlendMode: "screen" }} />
    <svg className="absolute inset-0 h-full w-full" viewBox="0 0 760 440" preserveAspectRatio="none" aria-label="Live route map">
      <g fill="none" stroke="#294550" strokeWidth="16" opacity=".72" strokeLinecap="round"><path d="M-20 370 L190 302 L350 350 L510 250 L780 290"/><path d="M35 80 L160 175 L360 115 L510 250 L700 90"/><path d="M250 -10 L285 140 L350 350"/><path d="M610 -10 L560 155 L510 250 L470 450"/></g>
      <g fill="none" stroke="#182e38" strokeWidth="5" opacity=".8"><path d="M-20 370 L190 302 L350 350 L510 250 L780 290"/><path d="M35 80 L160 175 L360 115 L510 250 L700 90"/><path d="M250 -10 L285 140 L350 350"/><path d="M610 -10 L560 155 L510 250 L470 450"/></g>
      <g fill="none" stroke="#48d7e8" strokeWidth="4" strokeDasharray="10 8" strokeLinecap="round"><path d="M88 335 L190 302 L350 350 L510 250 L640 272" /></g>
      <g fill="#ff806e" opacity=".65"><circle cx="207" cy="300" r="12"/><circle cx="438" cy="295" r="17"/><circle cx="606" cy="268" r="11"/></g>
      <g fill="#f5ba69" opacity=".65"><circle cx="362" cy="120" r="14"/><circle cx="535" cy="158" r="10"/></g>
      <g stroke="#48d7e8" strokeWidth="2" fill="#0c1d26"><circle cx="190" cy="302" r="9"/><circle cx="350" cy="350" r="9"/><circle cx="510" cy="250" r="9"/><circle cx="640" cy="272" r="9"/></g>
      <g fontFamily="IBM Plex Mono" fontSize="11" fill="#a9d8de"><text x="165" y="287">J01</text><text x="329" y="334">J02</text><text x="488" y="234">J03</text><text x="620" y="255">J04</text></g>
      <g transform={`translate(${ambulanceX} ${ambulanceY})`} className="transition-transform duration-1000 ease-out"><circle r="16" fill="#48d7e8" opacity=".13" className="beacon"/><circle r="7" fill="#48d7e8"/><path d="M-4 -3 L8 0 L-4 3 Z" fill="#061219"/><text x="13" y="4" fontFamily="IBM Plex Mono" fontSize="10" fill="#e9feff">AMB-102</text></g>
      <g transform="translate(640 272)"><path d="M0 -16 L14 9 L-14 9 Z" fill="#0e1b24" stroke="#5be6a8" strokeWidth="2"/><path d="M0 -8 L0 4" stroke="#5be6a8" strokeWidth="2"/><circle cy="8" r="2" fill="#5be6a8"/></g>
    </svg>
    <div className="absolute left-4 top-4 flex items-center gap-2 rounded-lg border border-white/10 bg-[#071017]/75 px-3 py-2 backdrop-blur-md"><Crosshair size={14} className="text-[#48d7e8]"/><span className="mono text-[10px] uppercase tracking-[.14em] text-[#b8d5da]">Live city grid</span><span className="h-1.5 w-1.5 rounded-full bg-[#5be6a8] beacon"/></div>
    <div className="absolute right-4 top-4 flex gap-1.5"><button className="rounded-md border border-white/10 bg-[#071017]/75 p-2 text-[#91aab0] transition-colors hover:text-white"><PlusIcon /></button><button className="rounded-md border border-white/10 bg-[#071017]/75 p-2 text-[#91aab0] transition-colors hover:text-white"><MinusIcon /></button></div>
    <div className="absolute bottom-4 left-4 right-4 flex flex-wrap items-center justify-between gap-3 rounded-lg border border-white/10 bg-[#071017]/80 px-3 py-2.5 backdrop-blur-md"><div className="flex flex-wrap items-center gap-4 mono text-[9px] uppercase tracking-[.08em] text-[#86a5ad]"><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#48d7e8]"/>Optimal route</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#ff806e]"/>Congestion</span><span className="flex items-center gap-1.5"><i className="h-2 w-2 rounded-full bg-[#f5ba69]"/>Signal queue</span></div><span className="mono text-[10px] text-[#48d7e8]">3.2 km² monitored</span></div>
  </div>;
}
function PlusIcon() { return <span className="block text-sm leading-none">+</span>; }
function MinusIcon() { return <span className="block text-sm leading-none">−</span>; }

function CorridorTimeline() { const items = [{ id: "01", label: "Junction 01", state: "ACTIVE GREEN", tone: "green" }, { id: "02", label: "Junction 02", state: "PREPARING", tone: "amber" }, { id: "03", label: "Junction 03", state: "PRIORITY SCHEDULED", tone: "cyan" }, { id: "04", label: "Junction 04", state: "NORMAL", tone: "muted" }]; return <div className="panel rounded-xl p-4 sm:p-5"><SectionTitle eyebrow="Corridor orchestration" title="Green Corridor Status" action="Corridor"/><div className="relative grid grid-cols-2 gap-y-5 sm:grid-cols-4 sm:gap-y-0">{items.map((item, index) => <div key={item.id} className="relative flex items-center gap-2 sm:block"><div className="absolute left-[13px] top-7 hidden h-px w-[calc(100%-6px)] bg-white/10 sm:block" style={{ display: index === items.length - 1 ? "none" : undefined }} /><div className={`relative z-10 flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-[10px] mono ${item.tone === "green" ? "border-[#5be6a8] bg-[#5be6a8]/15 text-[#5be6a8]" : item.tone === "amber" ? "border-[#f5ba69] bg-[#f5ba69]/15 text-[#f5ba69]" : item.tone === "cyan" ? "border-[#48d7e8] bg-[#48d7e8]/15 text-[#48d7e8]" : "border-white/20 bg-white/5 text-[#91aab0]"}`}>{item.id}</div><div className="sm:mt-3"><p className="text-xs font-medium text-[#dcecef]">{item.label}</p><p className={`mono mt-1 text-[9px] tracking-[.05em] ${item.tone === "green" ? "text-[#5be6a8]" : item.tone === "amber" ? "text-[#f5ba69]" : item.tone === "cyan" ? "text-[#48d7e8]" : "text-[#76939c]"}`}>{item.state}</p></div></div>)}</div></div>; }

function AmbulanceCard({ elapsed }: { elapsed: number }) { const sec = Math.max(0, 272 - elapsed); const eta = `0${Math.floor(sec/60)}:${String(sec%60).padStart(2, "0")}`; return <div className="panel panel-hover rounded-xl p-4 sm:p-5"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="rounded-xl border border-[#ff806e]/25 bg-[#ff806e]/10 p-2.5 text-[#ff806e]"><Ambulance size={19}/></div><div><div className="flex items-center gap-2"><h3 className="font-semibold text-white">AMB-102</h3><StatusPill tone="coral">Emergency active</StatusPill></div><p className="mono mt-1 text-[10px] text-[#76939c]">LAST SYNC 14:32:08 · GPS LOCKED</p></div></div><button onClick={() => toast.success("AMB-102 telemetry copied to clipboard.")} className="text-[#76939c] transition-colors hover:text-white"><MoreHorizontal size={17}/></button></div><div className="mt-5 grid grid-cols-3 gap-2 border-y border-white/[.07] py-4"><div><p className="mono text-[9px] uppercase text-[#76939c]">Speed</p><p className="mt-1 text-sm font-semibold text-white">48 <span className="text-[10px] font-normal text-[#76939c]">km/h</span></p></div><div><p className="mono text-[9px] uppercase text-[#76939c]">Distance</p><p className="mt-1 text-sm font-semibold text-white">2.4 <span className="text-[10px] font-normal text-[#76939c]">km</span></p></div><div><p className="mono text-[9px] uppercase text-[#76939c]">ETA</p><p className="mt-1 text-sm font-semibold text-[#48d7e8]">{eta}</p></div></div><div className="mt-4 flex items-center justify-between gap-4"><div><p className="mono text-[9px] uppercase text-[#76939c]">Destination</p><p className="mt-1 text-sm text-[#dcecef]">City General Hospital</p></div><div className="text-right"><p className="mono text-[9px] uppercase text-[#76939c]">Priority</p><p className="mt-1 text-sm font-semibold text-[#ff806e]">P1 Critical</p></div></div></div>; }

function SignalControl({ signalIndex, onAction }: { signalIndex: number; onAction: (label: string) => void }) { const signals = [{ junction: "Junction 01", state: "ACTIVE GREEN", tone: "green", distance: "420 m", eta: "00:31" }, { junction: "Junction 02", state: "PREPARING", tone: "amber", distance: "1.1 km", eta: "01:18" }, { junction: "Junction 03", state: "PRIORITY SCHEDULED", tone: "cyan", distance: "1.8 km", eta: "02:46" }]; const current = signals[signalIndex % signals.length]; return <div className="panel rounded-xl p-4 sm:p-5"><SectionTitle eyebrow="Intersection control" title="Traffic Signal Control"/><div className="flex items-center justify-between rounded-lg border border-white/10 bg-black/10 p-3"><div className="flex items-center gap-3"><div className="relative flex h-9 w-7 flex-col items-center justify-center gap-1 rounded-md border border-white/15 bg-[#08131a]"><span className={`h-1.5 w-1.5 rounded-full ${current.tone === "coral" ? "bg-[#ff806e]" : "bg-white/15"}`}/><span className={`h-1.5 w-1.5 rounded-full ${current.tone === "amber" ? "bg-[#f5ba69]" : "bg-white/15"}`}/><span className={`h-1.5 w-1.5 rounded-full ${current.tone === "green" ? "bg-[#5be6a8] shadow-[0_0_8px_#5be6a8]" : "bg-white/15"}`}/></div><div><p className="mono text-[9px] uppercase text-[#76939c]">Current junction</p><p className="mt-1 text-sm font-medium text-white">{current.junction}</p></div></div><StatusPill tone={current.tone as any}>{current.state}</StatusPill></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-lg border border-white/[.07] bg-white/[.025] p-3"><p className="mono text-[9px] uppercase text-[#76939c]">Ambulance distance</p><p className="mt-1 text-sm font-medium text-white">{current.distance}</p></div><div className="rounded-lg border border-white/[.07] bg-white/[.025] p-3"><p className="mono text-[9px] uppercase text-[#76939c]">Predicted ETA</p><p className="mt-1 text-sm font-medium text-[#48d7e8]">{current.eta}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2"><button onClick={() => onAction("Signal returned to normal") } className="rounded-md border border-white/10 bg-white/[.03] px-2 py-2 text-[10px] text-[#9bb4b9] transition-all hover:border-white/25 hover:text-white">Return to Normal</button><button onClick={() => onAction("Green window extended by 30 seconds")} className="rounded-md border border-[#5be6a8]/25 bg-[#5be6a8]/[.06] px-2 py-2 text-[10px] text-[#5be6a8] transition-all hover:bg-[#5be6a8]/[.12]">Extend Green</button><button onClick={() => onAction("Manual override request sent")} className="rounded-md border border-[#ff806e]/25 bg-[#ff806e]/[.06] px-2 py-2 text-[10px] text-[#ff9688] transition-all hover:bg-[#ff806e]/[.12]">Manual Override</button></div></div>; }

function HospitalCard() { return <div className="panel panel-hover rounded-xl p-4 sm:p-5"><SectionTitle eyebrow="Care network" title="Hospital Coordination" action="Hospital"/><div className="flex items-center gap-3"><div className="rounded-lg border border-[#48d7e8]/20 bg-[#48d7e8]/[.08] p-2.5 text-[#48d7e8]"><Building2 size={18}/></div><div><p className="text-sm font-medium text-white">City General Hospital</p><p className="mono mt-1 text-[10px] text-[#76939c]">TRAUMA INTAKE · BAY 04</p></div><StatusPill tone="green">Acknowledged</StatusPill></div><div className="mt-4 grid grid-cols-2 gap-x-6 gap-y-3 text-xs"><div><p className="mono text-[9px] uppercase text-[#76939c]">Ambulance ID</p><p className="mt-1 text-[#dcecef]">AMB-102</p></div><div><p className="mono text-[9px] uppercase text-[#76939c]">Patient priority</p><p className="mt-1 text-[#ff806e]">P1 Critical</p></div><div><p className="mono text-[9px] uppercase text-[#76939c]">ETA</p><p className="mt-1 text-[#48d7e8]">04:32</p></div><div><p className="mono text-[9px] uppercase text-[#76939c]">Emergency team</p><p className="mt-1 text-[#5be6a8]">Notified · 14:29</p></div></div></div>; }

export default function Home() {
  const [elapsed, setElapsed] = useState(0); const [clock, setClock] = useState(new Date()); const [signalIndex, setSignalIndex] = useState(0); const [mobileNav, setMobileNav] = useState(false);
  useEffect(() => { const timer = setInterval(() => { setElapsed(v => (v + 1) % 240); setClock(new Date()); }, 1000); const signal = setInterval(() => setSignalIndex(v => v + 1), 4200); const first = setTimeout(() => toast("Corridor recalculated", { description: "Junction 02 is staging for the next ETA window.", icon: <Sparkles size={15} className="text-[#48d7e8]"/> }), 1800); return () => { clearInterval(timer); clearInterval(signal); clearTimeout(first); }; }, []);
  const progress = useMemo(() => (elapsed % 240) / 2.4, [elapsed]);
  const doAction = (message: string) => toast.success(message, { description: "Change logged to the live operations timeline." });
  return <div className="lifelane-shell flex min-h-screen">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[246px] shrink-0 -translate-x-full flex-col border-r border-white/[.08] bg-[#08131a] px-4 py-5 transition-transform duration-300 lg:relative lg:translate-x-0 ${mobileNav ? "translate-x-0" : ""}`}>
      <div className="flex items-center justify-between px-2"><div className="flex items-center gap-3"><div className="relative flex h-9 w-9 items-center justify-center overflow-hidden rounded-lg border border-[#48d7e8]/30 bg-[#0d2931]"><span className="absolute h-px w-8 rotate-[40deg] bg-[#48d7e8]"/><span className="absolute h-px w-8 -rotate-[40deg] bg-[#48d7e8]"/><span className="relative h-2.5 w-2.5 rotate-45 border-r-2 border-t-2 border-white"/></div><div><p className="text-[17px] font-bold tracking-[.13em] text-white">LIFELANE</p><p className="mono text-[8px] tracking-[.16em] text-[#6f9099]">CITY RESPONSE SYSTEM</p></div></div><button className="text-[#78959d] lg:hidden" onClick={() => setMobileNav(false)}><X size={18}/></button></div>
      <div className="mt-10 px-2"><p className="mono mb-3 text-[9px] uppercase tracking-[.18em] text-[#52727b]">Operations</p>{navItems.map(({ label, icon: Icon, active }) => <button key={label} onClick={() => !active && toast.info(`${label} module is connected to the command center.`)} className={`group mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-[13px] transition-all ${active ? "border border-[#48d7e8]/20 bg-[#48d7e8]/[.09] text-[#e7fdff] shadow-[inset_3px_0_0_#48d7e8]" : "text-[#809ba3] hover:bg-white/[.04] hover:text-[#dcecef]"}`}><Icon size={16} strokeWidth={active ? 2 : 1.6} className={active ? "text-[#48d7e8]" : "text-[#6d8991] group-hover:text-[#48d7e8]"}/>{label}{active && <span className="ml-auto h-1.5 w-1.5 rounded-full bg-[#48d7e8] beacon"/>}</button>)}</div>
      <div className="mt-auto rounded-xl border border-[#48d7e8]/15 bg-[#48d7e8]/[.045] p-3"><div className="flex items-center gap-2"><ShieldCheck size={14} className="text-[#5be6a8]"/><span className="mono text-[9px] uppercase tracking-[.12em] text-[#9cc0c5]">Network protected</span></div><p className="mt-2 text-[11px] leading-relaxed text-[#6f8e96]">All corridors are encrypted and monitored across the city grid.</p><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[82%] rounded-full bg-[#48d7e8]"/></div></div>
      <div className="mt-4 flex items-center justify-between px-2 mono text-[9px] text-[#4e6d76]"><span>v2.4.08</span><span>OPS-01</span></div>
    </aside>
    {mobileNav && <button className="fixed inset-0 z-30 bg-black/50 lg:hidden" onClick={() => setMobileNav(false)} aria-label="Close navigation"/>}
    <main className="min-w-0 flex-1">
      <header className="flex h-[72px] items-center justify-between border-b border-white/[.08] bg-[#071017]/80 px-4 backdrop-blur-xl sm:px-7"><div className="flex items-center gap-3"><button className="rounded-lg border border-white/10 p-2 text-[#8ca8af] lg:hidden" onClick={() => setMobileNav(true)}><Menu size={18}/></button><div><p className="mono text-[9px] uppercase tracking-[.18em] text-[#48d7e8]">Live corridor orchestration</p><h1 className="mt-1 text-lg font-semibold tracking-[-.025em] text-white sm:text-xl">Emergency traffic state is active.</h1><p className="mono mt-1 text-[9px] uppercase tracking-[.1em] text-[#6f8e96]">04 events · 03 corridors · metro grid synchronized</p></div></div><div className="flex items-center gap-3 sm:gap-5"><div className="hidden items-center gap-2 sm:flex"><span className="h-2 w-2 rounded-full bg-[#5be6a8] beacon"/><span className="mono text-[10px] uppercase tracking-[.12em] text-[#acd2d5]">System online</span></div><div className="hidden h-5 w-px bg-white/10 sm:block"/><div className="mono hidden items-center gap-2 text-[11px] text-[#89a5ac] md:flex"><Clock3 size={14} className="text-[#48d7e8]"/>{clock.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false })}</div><button onClick={() => toast("No new critical alerts", { description: "All current emergency events are acknowledged." })} className="relative rounded-lg border border-white/10 bg-white/[.025] p-2.5 text-[#91aab0] transition-colors hover:text-white"><Bell size={16}/><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-[#ff806e]"/></button><div className="flex items-center gap-2 border-l border-white/10 pl-3"><div className="flex h-8 w-8 items-center justify-center rounded-full border border-[#48d7e8]/25 bg-[#12333b] text-xs font-semibold text-[#9beaf0]">AS</div><div className="hidden sm:block"><p className="text-xs font-medium text-white">Alex Smith</p><p className="mono text-[9px] text-[#6f8e96]">ADMIN · SHIFT A</p></div></div></div></header>
      <div className="mx-auto max-w-[1560px] px-4 py-5 sm:px-7 sm:py-7"><div className="mb-5 grid grid-cols-2 gap-3 xl:grid-cols-4"><MetricCard icon={Siren} label="Active emergencies" value="04" detail="1 critical response" accent="coral"/><MetricCard icon={Ambulance} label="Active ambulances" value="12" detail="3 units in motion"/><MetricCard icon={Navigation} label="Active green corridors" value="03" detail="Junctions synchronized" accent="green"/><MetricCard icon={Timer} label="Average time saved" value="07:42" detail="+18% vs. baseline"/></div>
        <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(350px,.8fr)]"><section className="min-w-0"><div className="mb-3 flex items-center justify-between"><div><p className="mono text-[10px] uppercase tracking-[.18em] text-[#48d7e8]">Live operations / metro grid</p><h2 className="mt-1 text-xl font-semibold tracking-[-.03em] text-white sm:text-2xl">Corridor overview</h2></div><StatusPill tone="green">Realtime feed</StatusPill></div><LiveMap progress={progress}/><div className="mt-5"><CorridorTimeline/></div></section><aside className="space-y-5"><AmbulanceCard elapsed={elapsed}/><SignalControl signalIndex={signalIndex} onAction={doAction}/><HospitalCard/></aside></div>
        <section className="mt-5 panel rounded-xl p-4 sm:p-5"><SectionTitle eyebrow="Response queue" title="Active Emergencies" action="Emergency queue"/><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-white/[.07] mono text-[9px] uppercase tracking-[.14em] text-[#6f8e96]"><th className="pb-3 pl-2 font-normal">Priority</th><th className="pb-3 font-normal">Ambulance ID</th><th className="pb-3 font-normal">Destination</th><th className="pb-3 font-normal">ETA</th><th className="pb-3 font-normal">Status</th><th className="pb-3 pr-2 text-right font-normal">Action</th></tr></thead><tbody>{emergencies.map((row) => <tr key={row.id} className="border-b border-white/[.05] text-xs last:border-0 hover:bg-white/[.018]"><td className="py-3.5 pl-2"><span className={`mono text-[10px] font-semibold ${row.priority === "P1" ? "text-[#ff806e]" : row.priority === "P2" ? "text-[#f5ba69]" : "text-[#48d7e8]"}`}>{row.priority}</span></td><td className="py-3.5 mono text-[#dcecef]">{row.id}</td><td className="py-3.5 text-[#abc4c9]">{row.destination}</td><td className="py-3.5 mono text-[#48d7e8]">{row.eta}</td><td className="py-3.5"><div className="flex items-center gap-2"><span className={`h-1.5 w-1.5 rounded-full ${row.tone === "coral" ? "bg-[#ff806e]" : row.tone === "amber" ? "bg-[#f5ba69]" : "bg-[#48d7e8]"} ${row.tone === "coral" ? "beacon" : ""}`} /><StatusPill tone={row.tone as any}>{row.status}</StatusPill></div></td><td className="py-3.5 pr-2 text-right"><button onClick={() => toast.info(`${row.id} selected`, { description: `Opening live telemetry for ${row.destination}.` })} className="rounded-md p-1.5 text-[#708e96] transition-colors hover:bg-white/5 hover:text-[#48d7e8]"><MoreHorizontal size={16}/></button></td></tr>)}</tbody></table></div></section>
        <footer className="flex flex-col gap-2 py-5 mono text-[9px] uppercase tracking-[.1em] text-[#4f6e77] sm:flex-row sm:items-center sm:justify-between"><span>Signal Noir interface · LIFELANE operations network</span><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#5be6a8]"/>All systems nominal</span></footer>
      </div>
    </main>
  </div>;
}
